error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
Command terminated by signal 11
	Command being timed: "python /home/cpennycu/networkx/gt.py -f /home/cpennycu/gdata/er/erd-4-10-32.snap -d 1"
	User time (seconds): 0.50
	System time (seconds): 0.14
	Percent of CPU this job got: 78%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.82
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 62644
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 23248
	Voluntary context switches: 46
	Involuntary context switches: 126
	Swaps: 0
	File system inputs: 8
	File system outputs: 16
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
